spring.application.name=EcommerceBackend
 #spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
#spring.datasource.username=arun
#spring.datasource.password=123
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

#spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#server.port=8082 

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}